### ISSUE TITLE
`navigate` is not exported

### ISSUE THREAD

**Issue by misantronic** [basarat/yester#15]
Unfortunately `import { navigate } from 'yester';` is not working because `navigate` is not exported.

**Comment by mattoni** [comment]
Hi @misantronic,
Not sure what you mean. You need to have an instance of the Router class, which has a public method `navigate` on it.

**Comment by basarat** [comment]
@mattoni can I migrate this project over to your github. I've forked the last version I worked on as my teams don't have the need for the new features (server side etc) :rose:

**Comment by basarat** [comment]
Fork is here : https://github.com/basarat/takeme 👍

**Comment by basarat** [comment]
@mattoni I cannot transfer as you have a fork active. Once you delete that I will hand over the keys 👑 🔑 🗝 :rose:

![image](https://user-images.githubusercontent.com/874898/29651195-c78f3dc6-88e2-11e7-91f3-da1a95d3dfcc.png)

**Comment by mattoni** [comment]
Hey @basarat,

I deleted the repo, thanks for giving me control! I'll treat it well. :)

**Comment by basarat** [comment]
Transferred, You should get a notification to accept :rose: 

![image](https://user-images.githubusercontent.com/874898/29712664-47bb743c-89de-11e7-9bb2-16fc56250de5.png)

**Comment by mattoni** [comment]
@basarat I don't see a notification for it, are you sure it went through?

**Comment by basarat** [comment]
Help : https://help.github.com/articles/about-repository-transfers/

@mattoni I see its done now so no action needed :rose:
