### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by tomitrescak** [basarat/yester#3]
Hello. took yester for a spin and ran into couple issues:

First, the route matching did not work properly.
In following:

```
const router = new Router([
  {
    $: '/',
    enter: () => {
      // executes this
    }
  },
  {
    $: '/:name/:path',
    enter: ({ params }) => {
      // and not this ;(
    }
  },
]);
```

When entering route '/my/example' it will match the root route and not the  correct child route.

Also, is it possible to fitch that ugly hash from the route? E.g. by specifying root url to router which would mark the beginning of parameters? If no root url would be specified, then it would take anything after the domain name.

**Comment by basarat** [comment]
First off, Thanks for trying! :heart: 💯 

> When entering route '/my/example' it will match the root route and not the correct child route.

Intentional. Routes are tested in order (hence an array). Mentioned here http://basarat.com/yester/#/?id=ordering-routes

> Also, is it possible to fitch that ugly hash from the route

Created an issue : https://github.com/basarat/yester/issues/4 :heart:
