### ISSUE TITLE
Support html5 routing

### ISSUE THREAD

**Issue by basarat** [basarat/yester#4]
Currently does hash routing only. Main reason I didn't *just do it* is that with html5 routing you need to add `onClick` handlers to anchors to intercept - prevent default - and call `pushState` :rose:

The docs mention that currently it only does `#/` routing http://basarat.com/yester/#/?id=what-does-it-support

**Comment by Hotell** [comment]
any progress on this?

**Comment by mattoni** [comment]
I'm beyond frustrated with React Router v4. Initially it seems like a great idea but 3/4 applications of mine need to know what data to load before mounting the components to avoid a waterfall effect. As an avid user of Typescript and your libraries @basarat , having a TS native router that can solve the pain points of react router would be incredible. The only thing this is missing is html5 routing!

What are the chances of making this happen? I know I'm not the only TS user out there looking for a better routing option :)

**Comment by mattoni** [comment]
Since I'm really interested in making this happen, I'm going to fork the repo and work on it. @basarat would you be opposed to using https://github.com/reacttraining/history under the hood? It would make yester a candidate for SSR as well.

**Comment by basarat** [comment]
@mattoni go for it. I really wish someone else solves this problem for me all of us :) 🌹❤🙌🏻

Sorry for the radio silence. Im in a cave for the next week working on something💜👌🏻

**Comment by mattoni** [comment]
@basarat check out the merge request and let me know if that's the direction you want to go in :)

**Comment by basarat** [comment]
I added support for html5 routing in the yester fork I created : http://basarat.com/takeme/#/?id=html5-routing if anyone is still interested :rose:
