### ISSUE TITLE
Router should kick off initial route

### ISSUE THREAD

**Issue by mweststrate** [basarat/yester#5]
First of all, great work! Tried it in a small project and it is really nice to set up and fits very well in the MobX philosophy!

I noticed that the initial route doesn't seem to be interpreted by the router yet; it now listens for history changes, but doesn't interpret the initial state. In your demo you can see that by clicking back after going to the first user. If you go to `John`, and press back, the url changes, but the route isn't interpreted and the app stays in the same state.

**Comment by basarat** [comment]
> First of all, great work! Tried it in a small project and it is really nice to set up and fits very well in the MobX philosophy!

As always ... thank *you* for mobx :rose: :heart:

The bug was that `http://something/` didn't match `*` or `/`. It worked first time because I initialized the state to `login` but didn't trigger after someone goes to `/`.  Fixed with `0.7.0`. Thanks for catching :rose: :heart:
