### ISSUE TITLE
Root path should match only empty or single slash

### ISSUE THREAD

**Issue by suzuki11109** [basarat/yester#6]
😄  Thanks for your library, awesome, but I got some problem.

I set up routes like this.
```
const router = new Router([
  {
    $: "/about",
    enter: () => {
      appState.currentView = { name: "about" }
    }
  },
  {
    $: "/",
    enter: () => {
      appState.currentView = { name: "main" }
    }
  },
  {
    $: "*",
    enter: () => {
      appState.currentView = { name: "notfound" }
    }
  },
]);
```

If I access url with root path like http://localhost or http://localhost#/, I will go to "main". That's great.
But if I access with the url that is not matched with anyone of them, It's just go to "main". 
I expect it to go to "*". Is there a way to do that?

Thanks.

**Comment by suzuki11109** [comment]
I read the code and I've seen that the "match" function returns the "remainingPath". You commented that it's for continuing matching but its caller in index.ts doesn't do like that, it doesn't even use it. So I tried to check the remainingPath index.ts, just before "entering", that if there is any remainingPath returns, it will continue the loop to check next routes. 
The code is like this.
```
      /** entering */
      const enterMatch = match({ pattern, path: newPath });
      if (enterMatch) {
        if (enterMatch.remainingPath) {
          continue;
        }
```
And it works. The random urls go to "*" matching. 😄

**Comment by suzuki11109** [comment]
I've created pull request #7 for the example code above.

**Comment by basarat** [comment]
`0.9.0` :rose: Thanks @suzuki11109 :heart:
